#!/bin/bash

usage() {
  echo "Usage: source ./setup_R [-v=VERSION] [-l] [-h]"
  echo "  -v=VERSION     setup VERSION version of R scdb. If"
  echo "                 VERSION is \"current\", the latest stable"
  echo "                 version will be setup."
  echo "  -l             list available versions"
  echo "  -h,            print this help."
  echo
}

if [[ $(hostname) == "dactyl.cshl.edu" ]]; then
  prefix="/tyronedata"
else
  prefix="/data"
fi
if (( $# == 0 )); then
  usage
elif (( $# == 1 )); then
  arg=$1
  if [[ ${arg:0:2} == "-v" ]]; then
    arg=${arg:2:${#arg}}
    if [[ ${arg:0:1} == "=" ]]; then
      arg=${arg:1:${#arg}}
    fi
    if (( ${#arg} == 0 )); then
      echo "ERROR: No version was passed!"
    else
      if [[ $arg != "current" && $arg != "devel" && ${arg:0:1} != "v" ]]; then
        arg="v$arg"
      fi
      if [[ -d "/data/single_cell_database/src/$arg" ]]; then
	R CMD INSTALL "$prefix/single_cell_database/src/$arg/R/scdb"
      else
        echo "ERROR: $arg is not a valid version!"
      fi
    fi
  elif [[ ${arg:0:2} == "-l" ]]; then
    for version in $(ls $prefix/single_cell_database/src/ | sort); do
      if [[ $version == "setup" ]]; then
        continue
      fi
      if [[ $version == "current" ]]; then
        echo "$version -> $(readlink $prefix/single_cell_database/src/current)"
      else
        echo $version
      fi
    done
  elif [[ ${arg:0:2} == "-h" ]]; then
    usage
  else
    echo "ERROR: Invalid argument!"
    echo
    usage
  fi
else
  echo "ERROR: Only 0 or 1 argument allowed!"
  echo
  usage
fi
